[package]
name = "view"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT"
description = "a macro for constructing views"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
