[package]
name = "view_macro"
version = "0.1.2"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "a macro for constructing views"
repository = "https://github.com/richardanaya/view/"

[dependencies]
proc-macro-hack = "0.5"

[lib]
proc-macro = true